version: "3.9"
services:
    app-service:
        container_name: app-container
        image: app-image
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:3000" 